---
- name: "Download latest aws cli"
  shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  args:
    chdir: $HOME

- name: "Unzip aws cli"
  shell: unzip awscliv2.zip
  args:
    chdir: $HOME

- name: "Install aws cli"
  shell: ./aws/install
  args:
    chdir: $HOME
