- name: "Deployment Application Configuration"
  hosts: management[0]
  user: ubuntu
  gather_facts: false
  become: yes
  vars:
    ENVIRONMENT_NAME: "{{ lookup('env', 'ENVIRONMENT_NAME') }}"
    DOCKER_IMAGE: "{{ lookup('env', 'DOCKER_IMAGE') }}"

  tasks:
    - name: run build
      shell: "./bin/kubectl set image deployments/{{ ENVIRONMENT_NAME }}-deployment {{ ENVIRONMENT_NAME }}-app=nhanct79/{{ DOCKER_IMAGE }}:latest"
      args:
        chdir: $HOME
    - name: if successful
      shell: "./bin/kubectl rollout status deployments/{{ ENVIRONMENT_NAME }}-deployment"
      args:
        chdir: $HOME
