apiVersion: apps/v1
kind: Deployment

metadata:
  name: project5-deployment
  labels:
    app: project5-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: project5-app

  template:
    metadata:
      labels:
        app: project5-app
    spec:
      containers:
        - name: project5-app
          image: nhanct79/project-5-ci-cd-springboot
          ports:
            - containerPort: 8080
